### ISSUE TITLE
Klingel kann noch komplett abstürzen

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/DoorBell#2]
Wir brauchen einen besseren Failsafe! Am Sonntag ging die Klingel überhaupt nicht, erst als ich das Kabel zur "Festplatten-Box" aus- und wieder eingesteckt habe konnte man wieder klingeln.

Ob das an der Elektronik oder der Software liegt müssten natürlich die, die sich damit etwas auskennen, ausknobeln - also hab ich euch mal alle assigned ;-)

Martin hat außerdem vorgeschlagen, eine Umschaltmöglichkeit zur alten Klingel einzurichten - in Fällen wie diesem, wenn jemand ohne viel Ahnung ein Problem bemerkt, könnte dann erstmal wieder analog gefahren werden und die Experten haben weniger Druck...

**Comment by emka** [comment]
Mir fehlt hier die Übersicht, den Klassik-Modus als Fallback finde ich aber auch sinnvoll.

**Comment by NitramLegov** [comment]
@Narquadah hat einen Reboot der Klingel nach 8 Stunden eingefügt, das hat leider nicht geholfen :(
Daher haben wir als neue Maßnahmen:
@Narquadah Hat sich drangesetzt, den Code zu Refactorn (Siehe https://github.com/comakingspace/DoorBell/tree/refactor) . Der ist im Rahmen der Tests der verschiedenen MQTT Clients etwas....chaotisch....geworden. Die Hoffnung ist, dass im Rahmen des Refactorings irgendein seltsamer Bug gefixt wird.

Außerdem hat @Johannes09 versprochen, die Elektronik so umzubauen, dass sie das 9V Wechselspannungssignal der original Klingel abgreift. Damit sind dann die Voraussetzungen geschaffen, einfach zwischen neuer und alter Klingel hin und her schalten zu können.

**Comment by Johannes09** [comment]
Provisorische Lösung damit die Klingel immer gehört wird auch wenn der Klingel-cood versagt.
![photo_2019-02-16_10-52-07](https://user-images.githubusercontent.com/22060480/52897984-f08d4d80-31d8-11e9-8340-4032ef1da008.jpg)

**Comment by NitramLegov** [comment]
@Narquadah hat sein refactoring soweit abgeschlossen, das scheint auch recht stabil zu laufen bisher. Habe heute noch ein/zwei bugs gefixt, insofern sollte es code-technisch jetzt hoffentlich passen.
Den Ringtone randomizer habe ich auch getestet, der läuft auch. Meiner Meinung nach kann man den code aus dem refactor branch jetzt in Master übernehmen.

**Comment by LukasFreeze** [comment]
Cool, wäre schön wenn das klappt!

Ich hätte gerne trotzdem noch einen hardwareseitigen Failsafe über die
mechanische Klingel. Gerne per default ausgestöpselt wenn sich der neue
Code ein paar Wochen lang bewährt hat, aber leicht zu aktivieren für jeden
Laien der einen Ausfall bemerkt.

**Comment by NitramLegov** [comment]
Absolut. Ich bin nach wie vor der Meinung, dass es einen Schalter braucht, der zwischen alter und neuer Klingel umschaltet. Falls dann die neue ausfällt kann jeder einfach den Schalter umstellen und wir haben Zeit, die neue entsprechend zu fixen. Dass beide Klingeln klingeln kann wie Johannes geschrieben hat ja nur ein Provisorium sein :)

**Comment by LukasFreeze** [comment]
Ich könnte so einen netten dreipoligen Kippschalter beisteuern, wenn der
euch ins Konzept passt :-)

https://tse4.mm.bing.net/th?id=OIP.vkwj3OcW1janap_HBljosAHaHa&pid=Api

**Comment by NitramLegov** [comment]
@Johannes09 hat heute die Verkabelung neu gemacht und den Schalter eingebaut:
![DSC_0625](https://user-images.githubusercontent.com/7809163/58765092-4828ac80-856f-11e9-8e42-d85485564d1b.JPG)
![DSC_0626](https://user-images.githubusercontent.com/7809163/58765093-4828ac80-856f-11e9-936f-dc5a066b6311.JPG)


Damit gibt es jetzt die einfache Möglichkeit, im Fehlerfall auf die alte Klingel umzuschalten.
